version: "3"
services:
    app:
      build: .
      container_name: app
      ports:
        - 8080:8080
      depends_on:
        - db
      environment:
        - POSTGRESQL_HOST=${POSTGRESQL_HOST}
        - POSTGRESQL_USERNAME=${POSTGRESQL_USERNAME}
        - POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD}
        - POSTGRESQL_PORT=${POSTGRESQL_PORT}
        - POSTGRESQL_DB_NAME=${POSTGRESQL_DB_NAME}
        - REDIS_HOST=${REDIS_HOST}
        - REDIS_PORT=${REDIS_PORT}
        - REDIS_PASS=${REDIS_PASS}
        - REDIS_TIME_TO_LIVE=${REDIS_TIME_TO_LIVE}
    db:
      image: 'postgres:13.1-alpine'
      container_name: db
      ports:
        - 5433:${POSTGRESQL_PORT}
      environment:
        - POSTGRES_USER=${POSTGRESQL_USERNAME}
        - POSTGRES_PASSWORD=${POSTGRESQL_PASSWORD}
        - POSTGRES_DB=${POSTGRESQL_DB_NAME}
      volumes:
        - private_db_volume:/var/lib/postgresql/data
    cache:
      image: 'redis:7.2-alpine'
      container_name: cache
      restart: always
      ports:
        - ${REDIS_PORT}:${REDIS_PORT}
      command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASS}
      volumes:
        - cache:/data
volumes:
  private_db_volume:
  cache:
    driver: local
