version: "3"
services:
    app:
      build: .
      container_name: app
      ports:
        - 8080:8080
      depends_on:
        - db
      environment:
        - POSTGRESQL_HOST=${POSTGRESQL_HOST}
        - POSTGRESQL_USERNAME=${POSTGRESQL_USERNAME}
        - POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD}
        - POSTGRESQL_PORT=${POSTGRESQL_PORT}
        - POSTGRESQL_DB_NAME=${POSTGRESQL_DB_NAME}
    db:
      image: 'postgres:13.1-alpine'
      container_name: db
      ports:
        - 5433:${POSTGRESQL_PORT}
      environment:
        - POSTGRES_USER=${POSTGRESQL_USERNAME}
        - POSTGRES_PASSWORD=${POSTGRESQL_PASSWORD}
        - POSTGRES_DB=${POSTGRESQL_DB_NAME}
      volumes:
        - private_db_volume:/var/lib/postgresql/data
volumes:
    private_db_volume:
